linux-build:
    stage: build
    image: registry.gitlab.com/linux-wiiu/linux-wiiu-scripts/lw-ci:latest
    variables:
        GIT_DEPTH: 2
    script:
        - make wiiu_defconfig $LINUXMK
        - make $LINUXMK -j`nproc`
        - cp arch/powerpc/boot/dtbImage.wiiu dtbImage.wiiu
    artifacts:
        paths:
            - dtbImage.wiiu
            - vmlinux
        name: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
        expire_in: 6 weeks

linux-build-modular:
    stage: build
    image: registry.gitlab.com/linux-wiiu/linux-wiiu-scripts/lw-ci:latest
    variables:
        GIT_DEPTH: 2
    script:
        - mkdir modules
        - make wiiu_slim_defconfig $LINUXMK
        - make $LINUXMK -j`nproc`
        - make $LINUXMK modules_install INSTALL_MOD_PATH=modules
        - cp arch/powerpc/boot/dtbImage.wiiu dtbImage.wiiu
    artifacts:
        paths:
            - dtbImage.wiiu
            - vmlinux
            - modules
        name: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
        expire_in: 6 weeks
