linux-build:
    stage: build
    image: quarktheawesome/linux-wiiu-builder:v2
    variables:
        GIT_DEPTH: 2
    script:
        - make wiiu_defconfig $LINUXMK
        - make $LINUXMK
        - cp arch/powerpc/boot/dtbImage.wiiu dtbImage.wiiu
    artifacts:
        paths:
            - dtbImage.wiiu
            - vmlinux
        name: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
        expire_in: 6 weeks