linux-build:
    stage: build
    image: registry.gitlab.com/linux-wiiu/linux-wiiu-scripts/lw-ci:latest
    variables:
        GIT_DEPTH: 2
    script:
        - make wiiu_defconfig $LINUXMK
        - make $LINUXMK
        - cp arch/powerpc/boot/dtbImage.wiiu dtbImage.wiiu
    artifacts:
        paths:
            - dtbImage.wiiu
            - vmlinux
        name: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
        expire_in: 6 weeks

linux-build-modular:
    stage: build
    image: registry.gitlab.com/linux-wiiu/linux-wiiu-scripts/lw-ci:latest
    variables:
        GIT_DEPTH: 2
    script:
        - mkdir modules
        - make wiiu_slim_defconfig $LINUXMK
        - make $LINUXMK
        - make $LINUXMK modules_install INSTALL_MOD_PATH=modules
        - cp arch/powerpc/boot/dtbImage.wiiu dtbImage.wiiu
    artifacts:
        paths:
            - dtbImage.wiiu
            - vmlinux
            - modules
        name: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
        expire_in: 6 weeks

linux-build-debian:
    stage: build
    image: registry.gitlab.com/linux-wiiu/linux-wiiu-scripts/lw-ci:latest
    before_script:
        - apt update && apt -y install openssh-client git
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        - eval $(ssh-agent -s)
        - echo "$BOT_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - export PKG_REV=$(git shortlog HEAD | grep -E '^[ ]+\w+' | wc -l)
        - mkdir modules
        - make wiiu_slim_defconfig $LINUXMK
        - make $LINUXMK bindeb-pkg KBUILD_IMAGE=arc/powerpc/boot/dtbImage.wiiu DEBFULLNAME="Ash Logan" DEBEMAIL="ash@linux-wiiu.org" KDEB_CHANGELOG_DIST="unstable" KDEB_PKGVERSION=$PKG_REV
        - git clone git@gitlab.com:linux-wiiu/debian-wiiu-repo
        - mv ../*.deb ../*.buildinfo debian-wiiu-repo/debs/
        - cd debian-wiiu-repo && git add debs/* && git commit -m "Add kernel r${PKG_REV} from ${CI_PROJECT_PATH}/${CI_COMMIT_SHA}" && git push
    artifacts:
        paths:
            - ./*.deb
            - ./*.buildinfo
        name: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
        expire_in: 6 weeks
