name: CFW Kernel Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Install Packages
      run: sudo apt install git gcc-10-powerpc-linux-gnu gcc-powerpc-linux-gnu make gcc flex binutils bison libssl-dev
    - name: Configure CFW Kernel
      run: make wiiu_slim_defconfig ARCH=powerpc CROSS_COMPILE=powerpc-linux-gnu- CROSS32_COMPILE=powerpc-linux-gnu- -j$(nproc)
    - name: Build CFW Kernel
      run: make ARCH=powerpc CROSS_COMPILE=powerpc-linux-gnu- CROSS32_COMPILE=powerpc-linux-gnu- -j2
    - name: Add Modules
      run: mkdir modules
    - name: Compile Modules
      run: make ARCH=powerpc CROSS_COMPILE=powerpc-linux-gnu- CROSS32_COMPILE=powerpc-linux-gnu- INSTALL_MOD_PATH=modules modules_install -j2
